baseURL = 'https://mugongo.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Kyengera Parents School - Mugongo'
theme = "C:\\Users\\timot\\SAKS_web\\sirapollokaggwaschools\\themes\\saks-theme"


[params]
logo = "/img/logo.png"
mainSchool = false
defaultDescription = "Kyengera Parents school-Mugongo is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level."
    [params.school]
        hm_name = "MPERESE JOHN BOSCO"
        name = "mugongo"
        motto = 'Education with a Purpose'
        mission = 'To be a leading school in the provision of quality education'
        vision = 'The vision of Kyengera Parents School, Mugongo is to produce devoted learners in academics, moral education and life skills, leadership skills, creativity, and innovation, honest and humble, self-driven with a positive attitude towards quality work.'
        summary1 = 'Kyengera Parents school-Mugongo is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level. The school has two sections i.e pre-school and Primary school.'
        summary2 = 'At Kyengera Parents School, Mugongo, we are always learning through a holistic curriculum where individual talents are celebrated and nurtured. Working together as one team, in a caring, yet stimulating environment, we ensure that as an organization, excellence is the expectation. Our network of strong pastoral support fulfills the ambitions of students so that graduates go on to make a positive difference to the world in which they live.'
        hm = "Dear parents/guardians, staff and pupils, it is with immense pride and joy that we address you through this special school handle.  We are thrilled to extend our warm welcome to each of you to our mighty school Kyengera Parents’ Mugongo. It is truly a privilege to serve as the Headteacher of such a vibrant and excelling educational institution."
    [params.carousel]
        two = "Offering a broad learning environment"
        three = "We train leaders by embracing smartness"
        four = "Offering the best learning skills to students"
        five = "Welcoming all types of students"
        six = "Interactive teachers that monitor pupils in all activities"
        